name: deploy-protected

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - qa
      helmfile_target:
        description: "Helmfile path to deploy (default: full helmfile.d/ directory)"
        required: false
        default: "helmfile.d/"
      sha:
        description: "Git SHA to deploy (default: current commit of selected branch)"
        required: false

jobs:
  deploy:
    environment: qa
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "REF: ${{ input.sha || github.sha }}"
          echo "ENV: ${{ inputs.environment }}"
          echo "HELMFILE_TARGET: ${{ inputs.helmfile_target }}"