name: deploy-regular

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
      helmfile_target:
        description: "Helmfile path to deploy (default: full helmfile.d/ directory)"
        required: false
        default: "helmfile.d/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "REF: ${{ github.sha }}"
          echo "ENV: ${{ inputs.environment }}"
          echo "HELMFILE_TARGET: ${{ inputs.helmfile_target }}"